/*
    QOA DEMO - SQL Server
    Script deliberadamente legado para una charla de modernizacion con IA.
    Contiene validaciones correctas de parametros, pero tambien cursores, WHILE,
    tablas variables, UDF escalares, filtros no SARGables y lecturas repetidas.
    Los indices de mejora estan al final y NO se ejecutan.
*/

IF DB_ID('QOA_DEMO') IS NULL
BEGIN
    CREATE DATABASE QOA_DEMO;
END
GO
USE QOA_DEMO;
GO

IF OBJECT_ID('dbo.POL_MOVIMIENTO', 'U') IS NOT NULL DROP TABLE dbo.POL_MOVIMIENTO;
IF OBJECT_ID('dbo.POL_POLIZA_COBERTURA', 'U') IS NOT NULL DROP TABLE dbo.POL_POLIZA_COBERTURA;
IF OBJECT_ID('dbo.POL_COBERTURA', 'U') IS NOT NULL DROP TABLE dbo.POL_COBERTURA;
IF OBJECT_ID('dbo.POL_VEHICULO', 'U') IS NOT NULL DROP TABLE dbo.POL_VEHICULO;
IF OBJECT_ID('dbo.POL_TARJETA', 'U') IS NOT NULL DROP TABLE dbo.POL_TARJETA;
IF OBJECT_ID('dbo.POL_POLIZA', 'U') IS NOT NULL DROP TABLE dbo.POL_POLIZA;
IF OBJECT_ID('dbo.POL_PERSONA', 'U') IS NOT NULL DROP TABLE dbo.POL_PERSONA;
IF OBJECT_ID('dbo.SEG_USUARIO', 'U') IS NOT NULL DROP TABLE dbo.SEG_USUARIO;
GO

CREATE TABLE dbo.SEG_USUARIO
(
    N_ID_USUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    C_USUARIO VARCHAR(50) NOT NULL,
    C_CLAVE VARCHAR(100) NOT NULL,
    C_NOMBRE_COMPLETO VARCHAR(200) NOT NULL,
    C_PERFIL VARCHAR(50) NOT NULL,
    C_CORREO VARCHAR(150) NULL,
    N_ACTIVO INT NOT NULL DEFAULT 1,
    D_FEC_REGISTRO DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE dbo.POL_PERSONA
(
    N_ID_PERSONA BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    C_TIPO_DOCUMENTO VARCHAR(10) NULL,
    C_NUM_DOCUMENTO VARCHAR(20) NOT NULL,
    C_NOMBRE_COMPLETO VARCHAR(200) NOT NULL,
    C_CORREO VARCHAR(150) NULL,
    C_TELEFONO VARCHAR(30) NULL,
    C_DIRECCION VARCHAR(300) NULL,
    N_ACTIVO INT NOT NULL DEFAULT 1,
    D_FEC_REGISTRO DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE dbo.POL_POLIZA
(
    N_ID_POLIZA BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    C_NUM_POLIZA VARCHAR(30) NOT NULL,
    C_TIPO_PRODUCTO VARCHAR(20) NOT NULL,
    N_ID_CONTRATANTE BIGINT NOT NULL,
    D_FEC_EMISION DATETIME NOT NULL,
    D_INI_VIGENCIA DATE NOT NULL,
    D_FIN_VIGENCIA DATE NOT NULL,
    N_PRIMA_NETA DECIMAL(18,2) NOT NULL,
    N_IGV DECIMAL(18,2) NOT NULL,
    N_PRIMA_TOTAL DECIMAL(18,2) NOT NULL,
    C_MONEDA VARCHAR(5) NOT NULL DEFAULT 'PEN',
    C_ESTADO VARCHAR(20) NOT NULL,
    C_OBSERVACION VARCHAR(1000) NULL,
    C_USUARIO_REGISTRO VARCHAR(50) NOT NULL,
    D_FEC_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    D_FEC_ANULACION DATETIME NULL,
    C_MOTIVO_ANULACION VARCHAR(500) NULL,
    N_ACTIVO INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_POLIZA_PERSONA FOREIGN KEY (N_ID_CONTRATANTE) REFERENCES dbo.POL_PERSONA(N_ID_PERSONA)
);

CREATE TABLE dbo.POL_TARJETA
(
    N_ID_TARJETA BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    N_ID_POLIZA BIGINT NOT NULL,
    C_BANCO VARCHAR(100) NULL,
    C_TIPO_TARJETA VARCHAR(50) NULL,
    C_ULTIMOS_DIGITOS CHAR(4) NULL,
    N_LINEA_CREDITO DECIMAL(18,2) NULL,
    C_PLAN VARCHAR(50) NULL,
    CONSTRAINT FK_TARJETA_POLIZA FOREIGN KEY (N_ID_POLIZA) REFERENCES dbo.POL_POLIZA(N_ID_POLIZA)
);

CREATE TABLE dbo.POL_VEHICULO
(
    N_ID_VEHICULO BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    N_ID_POLIZA BIGINT NOT NULL,
    C_PLACA VARCHAR(10) NULL,
    C_MARCA VARCHAR(50) NULL,
    C_MODELO VARCHAR(50) NULL,
    N_ANIO INT NULL,
    C_NUM_MOTOR VARCHAR(80) NULL,
    C_NUM_SERIE VARCHAR(80) NULL,
    N_VALOR_COMERCIAL DECIMAL(18,2) NULL,
    C_USO VARCHAR(30) NULL,
    CONSTRAINT FK_VEHICULO_POLIZA FOREIGN KEY (N_ID_POLIZA) REFERENCES dbo.POL_POLIZA(N_ID_POLIZA)
);

CREATE TABLE dbo.POL_COBERTURA
(
    N_ID_COBERTURA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    C_TIPO_PRODUCTO VARCHAR(20) NOT NULL,
    C_NOMBRE VARCHAR(200) NOT NULL,
    N_ACTIVO INT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.POL_POLIZA_COBERTURA
(
    N_ID_POLIZA_COBERTURA BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    N_ID_POLIZA BIGINT NOT NULL,
    N_ID_COBERTURA INT NOT NULL,
    N_ACTIVO INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_POLCOB_POLIZA FOREIGN KEY (N_ID_POLIZA) REFERENCES dbo.POL_POLIZA(N_ID_POLIZA),
    CONSTRAINT FK_POLCOB_COBERTURA FOREIGN KEY (N_ID_COBERTURA) REFERENCES dbo.POL_COBERTURA(N_ID_COBERTURA)
);

CREATE TABLE dbo.POL_MOVIMIENTO
(
    N_ID_MOVIMIENTO BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    N_ID_POLIZA BIGINT NOT NULL,
    C_TIPO_MOVIMIENTO VARCHAR(30) NOT NULL,
    C_DETALLE VARCHAR(2000) NULL,
    C_USUARIO VARCHAR(50) NULL,
    D_FEC_MOVIMIENTO DATETIME NOT NULL DEFAULT GETDATE()
);
GO

INSERT dbo.SEG_USUARIO(C_USUARIO,C_CLAVE,C_NOMBRE_COMPLETO,C_PERFIL,C_CORREO) VALUES ('admin','admin','Administrador Demo','EMISOR','admin@demo.local');
INSERT dbo.POL_COBERTURA(C_TIPO_PRODUCTO,C_NOMBRE) VALUES
('TARJETA','Compras no reconocidas'),('TARJETA','Robo en cajero'),('TARJETA','Fraude por internet'),
('VEHICULAR','Danos propios'),('VEHICULAR','Responsabilidad civil'),('VEHICULAR','Robo total');
GO

CREATE OR ALTER FUNCTION dbo.FN_CALCULAR_PRIMA_MALA
(
    @C_TIPO_PRODUCTO VARCHAR(20),
    @N_VALOR DECIMAL(18,2),
    @C_PLAN VARCHAR(50)
)
RETURNS DECIMAL(18,2)
AS
BEGIN
    DECLARE @N_RESULTADO DECIMAL(18,2) = 0;
    DECLARE @I INT = 1;
    -- Calculo repetitivo sin necesidad; la UDF escalar sera invocada fila por fila.
    WHILE @I <= 36
    BEGIN
        IF UPPER(LTRIM(RTRIM(@C_TIPO_PRODUCTO))) = 'TARJETA'
            SET @N_RESULTADO = CASE WHEN @C_PLAN = 'PLAN 1' THEN 29.90 WHEN @C_PLAN = 'PLAN 2' THEN 49.90 ELSE 69.90 END;
        ELSE
            SET @N_RESULTADO = ISNULL(@N_VALOR, 0) * 0.028;
        SET @I = @I + 1;
    END
    RETURN @N_RESULTADO;
END
GO

CREATE OR ALTER FUNCTION dbo.FN_DESCRIPCION_PRODUCTO_MALA(@N_ID_POLIZA BIGINT)
RETURNS VARCHAR(100)
AS
BEGIN
    DECLARE @T VARCHAR(20), @R VARCHAR(100);
    SELECT @T = C_TIPO_PRODUCTO FROM dbo.POL_POLIZA WHERE N_ID_POLIZA = @N_ID_POLIZA;
    SET @R = CASE WHEN @T = 'TARJETA' THEN 'Proteccion de Tarjeta' ELSE 'Seguro Vehicular' END;
    RETURN @R;
END
GO

CREATE OR ALTER PROCEDURE dbo.SPS_SEG_LOGIN
    @C_USUARIO VARCHAR(50),
    @C_CLAVE VARCHAR(100)
AS
BEGIN
    SET NOCOUNT OFF;
    IF @C_USUARIO IS NULL OR LTRIM(RTRIM(@C_USUARIO)) = '' THROW 50001, 'Debe enviar el usuario.', 1;
    IF @C_CLAVE IS NULL OR LTRIM(RTRIM(@C_CLAVE)) = '' THROW 50002, 'Debe enviar la clave.', 1;

    DECLARE @ID INT = NULL, @U VARCHAR(50), @P VARCHAR(100), @ACTIVO INT;
    DECLARE CUR_USUARIOS CURSOR LOCAL FOR SELECT N_ID_USUARIO,C_USUARIO,C_CLAVE,N_ACTIVO FROM dbo.SEG_USUARIO;
    OPEN CUR_USUARIOS;
    FETCH NEXT FROM CUR_USUARIOS INTO @ID,@U,@P,@ACTIVO;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        WAITFOR DELAY '00:00:00.050';
        IF LOWER(LTRIM(RTRIM(@U))) = LOWER(LTRIM(RTRIM(@C_USUARIO))) AND @P = @C_CLAVE AND @ACTIVO = 1 BREAK;
        SET @ID = NULL;
        FETCH NEXT FROM CUR_USUARIOS INTO @ID,@U,@P,@ACTIVO;
    END
    CLOSE CUR_USUARIOS; DEALLOCATE CUR_USUARIOS;

    SELECT * FROM dbo.SEG_USUARIO
    WHERE N_ID_USUARIO = @ID
      AND LOWER(LTRIM(RTRIM(C_USUARIO))) = LOWER(LTRIM(RTRIM(@C_USUARIO)));
END
GO

CREATE OR ALTER PROCEDURE dbo.SPI_POLIZA_EMITIR
    @C_TIPO_PRODUCTO VARCHAR(20), @C_DOCUMENTO VARCHAR(20), @C_NOMBRE VARCHAR(200),
    @D_INI_VIGENCIA DATE, @D_FIN_VIGENCIA DATE, @N_PRIMA_NETA DECIMAL(18,2),
    @C_BANCO VARCHAR(100) = NULL, @C_TIPO_TARJETA VARCHAR(50) = NULL, @C_ULTIMOS_DIGITOS CHAR(4) = NULL,
    @N_LINEA_CREDITO DECIMAL(18,2) = NULL, @C_PLAN VARCHAR(50) = NULL,
    @C_PLACA VARCHAR(10) = NULL, @C_MARCA VARCHAR(50) = NULL, @C_MODELO VARCHAR(50) = NULL,
    @N_ANIO INT = NULL, @C_NUM_MOTOR VARCHAR(80) = NULL, @C_NUM_SERIE VARCHAR(80) = NULL,
    @N_VALOR_COMERCIAL DECIMAL(18,2) = NULL, @C_USO VARCHAR(30) = NULL, @C_USUARIO VARCHAR(50),
    @PO_ID_POLIZA BIGINT OUTPUT
AS
BEGIN
    SET NOCOUNT OFF;
    IF @C_TIPO_PRODUCTO NOT IN ('TARJETA','VEHICULAR') THROW 50101, 'Tipo de producto invalido.', 1;
    IF @C_DOCUMENTO IS NULL OR LEN(LTRIM(RTRIM(@C_DOCUMENTO))) = 0 THROW 50102, 'Documento obligatorio.', 1;
    IF @C_NOMBRE IS NULL OR LEN(LTRIM(RTRIM(@C_NOMBRE))) < 3 THROW 50103, 'Nombre obligatorio.', 1;
    IF @D_INI_VIGENCIA IS NULL OR @D_FIN_VIGENCIA IS NULL OR @D_FIN_VIGENCIA <= @D_INI_VIGENCIA THROW 50104, 'Vigencia invalida.', 1;
    IF @C_TIPO_PRODUCTO = 'TARJETA' AND LEN(ISNULL(@C_ULTIMOS_DIGITOS,'')) <> 4 THROW 50105, 'Debe enviar cuatro digitos.', 1;
    IF @C_TIPO_PRODUCTO = 'VEHICULAR' AND LEN(LTRIM(RTRIM(ISNULL(@C_PLACA,'')))) = 0 THROW 50106, 'Placa obligatoria.', 1;

    DECLARE @N_ID_PERSONA BIGINT, @C_NUM_POLIZA VARCHAR(30), @N_CORRELATIVO BIGINT;
    -- Dos recorridos y COUNT para un correlativo que podria resolverse con IDENTITY/SEQUENCE.
    SELECT @N_CORRELATIVO = COUNT(*) + 1 FROM dbo.POL_POLIZA;
    SELECT @N_CORRELATIVO = @N_CORRELATIVO + COUNT(*) - COUNT(*) FROM dbo.POL_POLIZA;
    SET @C_NUM_POLIZA = CASE WHEN @C_TIPO_PRODUCTO='TARJETA' THEN 'PCT' ELSE 'VEH' END + '-' + CONVERT(VARCHAR(4),YEAR(GETDATE())) + '-' + RIGHT('000000' + CONVERT(VARCHAR(20),@N_CORRELATIVO),6);

    INSERT dbo.POL_PERSONA(C_TIPO_DOCUMENTO,C_NUM_DOCUMENTO,C_NOMBRE_COMPLETO) VALUES ('DNI',@C_DOCUMENTO,@C_NOMBRE);
    SET @N_ID_PERSONA = SCOPE_IDENTITY();

    -- Se ignora la prima recibida y se recalcula con una UDF deliberadamente lenta.
    SET @N_PRIMA_NETA = dbo.FN_CALCULAR_PRIMA_MALA(@C_TIPO_PRODUCTO, @N_VALOR_COMERCIAL, @C_PLAN);
    INSERT dbo.POL_POLIZA(C_NUM_POLIZA,C_TIPO_PRODUCTO,N_ID_CONTRATANTE,D_FEC_EMISION,D_INI_VIGENCIA,D_FIN_VIGENCIA,N_PRIMA_NETA,N_IGV,N_PRIMA_TOTAL,C_ESTADO,C_USUARIO_REGISTRO)
    VALUES(@C_NUM_POLIZA,@C_TIPO_PRODUCTO,@N_ID_PERSONA,GETDATE(),@D_INI_VIGENCIA,@D_FIN_VIGENCIA,@N_PRIMA_NETA,@N_PRIMA_NETA*0.18,@N_PRIMA_NETA*1.18,'EMITIDA',@C_USUARIO);
    SET @PO_ID_POLIZA = SCOPE_IDENTITY();

    IF @C_TIPO_PRODUCTO = 'TARJETA'
        INSERT dbo.POL_TARJETA(N_ID_POLIZA,C_BANCO,C_TIPO_TARJETA,C_ULTIMOS_DIGITOS,N_LINEA_CREDITO,C_PLAN) VALUES(@PO_ID_POLIZA,@C_BANCO,@C_TIPO_TARJETA,@C_ULTIMOS_DIGITOS,@N_LINEA_CREDITO,@C_PLAN);
    ELSE
        INSERT dbo.POL_VEHICULO(N_ID_POLIZA,C_PLACA,C_MARCA,C_MODELO,N_ANIO,C_NUM_MOTOR,C_NUM_SERIE,N_VALOR_COMERCIAL,C_USO) VALUES(@PO_ID_POLIZA,@C_PLACA,@C_MARCA,@C_MODELO,@N_ANIO,@C_NUM_MOTOR,@C_NUM_SERIE,@N_VALOR_COMERCIAL,@C_USO);

    DECLARE @T_COBERTURAS TABLE(FILA INT IDENTITY(1,1), N_ID_COBERTURA INT);
    INSERT @T_COBERTURAS(N_ID_COBERTURA)
        SELECT N_ID_COBERTURA FROM dbo.POL_COBERTURA WHERE UPPER(LTRIM(RTRIM(C_TIPO_PRODUCTO))) = UPPER(LTRIM(RTRIM(@C_TIPO_PRODUCTO))) AND N_ACTIVO=1;
    DECLARE @I INT=1,@TOTAL INT,@ID_COB INT;
    SELECT @TOTAL=COUNT(*) FROM @T_COBERTURAS;
    WHILE @I<=@TOTAL
    BEGIN
        SELECT @ID_COB=N_ID_COBERTURA FROM @T_COBERTURAS WHERE FILA=@I;
        INSERT dbo.POL_POLIZA_COBERTURA(N_ID_POLIZA,N_ID_COBERTURA) VALUES(@PO_ID_POLIZA,@ID_COB);
        SET @I=@I+1;
    END
    INSERT dbo.POL_MOVIMIENTO(N_ID_POLIZA,C_TIPO_MOVIMIENTO,C_DETALLE,C_USUARIO) VALUES(@PO_ID_POLIZA,'EMISION','Poliza emitida',@C_USUARIO);
END
GO

CREATE OR ALTER PROCEDURE dbo.SPS_POLIZA_CONSULTAR
    @C_FILTRO VARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT OFF;
    DECLARE @T_RESULTADO TABLE
    (
        N_ID_POLIZA BIGINT, C_NUM_POLIZA VARCHAR(30), C_TIPO_PRODUCTO VARCHAR(20), C_DES_PRODUCTO VARCHAR(100),
        C_DOCUMENTO VARCHAR(20), C_NOMBRE_COMPLETO VARCHAR(200), D_FEC_EMISION VARCHAR(30),
        N_PRIMA_NETA DECIMAL(18,2), N_PRIMA_TOTAL DECIMAL(18,2), C_ESTADO VARCHAR(20)
    );

    INSERT @T_RESULTADO
    SELECT P.N_ID_POLIZA,P.C_NUM_POLIZA,P.C_TIPO_PRODUCTO,dbo.FN_DESCRIPCION_PRODUCTO_MALA(P.N_ID_POLIZA),
           (SELECT X.C_NUM_DOCUMENTO FROM dbo.POL_PERSONA X WHERE X.N_ID_PERSONA=P.N_ID_CONTRATANTE),
           (SELECT X.C_NOMBRE_COMPLETO FROM dbo.POL_PERSONA X WHERE X.N_ID_PERSONA=P.N_ID_CONTRATANTE),
           CONVERT(VARCHAR(30),P.D_FEC_EMISION,103),P.N_PRIMA_NETA,P.N_PRIMA_TOTAL,P.C_ESTADO
    FROM dbo.POL_POLIZA P
    WHERE @C_FILTRO IS NULL OR @C_FILTRO=''
       OR LOWER(P.C_NUM_POLIZA) LIKE '%' + LOWER(@C_FILTRO) + '%'
       OR LOWER((SELECT X.C_NOMBRE_COMPLETO FROM dbo.POL_PERSONA X WHERE X.N_ID_PERSONA=P.N_ID_CONTRATANTE)) LIKE '%' + LOWER(@C_FILTRO) + '%'
       OR CONVERT(VARCHAR(20),(SELECT X.C_NUM_DOCUMENTO FROM dbo.POL_PERSONA X WHERE X.N_ID_PERSONA=P.N_ID_CONTRATANTE)) LIKE '%' + @C_FILTRO + '%';

    -- Ordenar una tabla variable sin estadisticas y devolver todo, sin paginacion.
    SELECT * FROM @T_RESULTADO ORDER BY D_FEC_EMISION DESC, C_NUM_POLIZA DESC;
END
GO

CREATE OR ALTER PROCEDURE dbo.SPS_POLIZA_DETALLE @N_ID_POLIZA BIGINT
AS
BEGIN
    SET NOCOUNT OFF;
    IF @N_ID_POLIZA IS NULL OR @N_ID_POLIZA <= 0 THROW 50201, 'Id de poliza invalido.', 1;

    -- La misma tabla se relee mediante subconsultas escalares para cada columna relacionada.
    SELECT P.*,
           dbo.FN_DESCRIPCION_PRODUCTO_MALA(P.N_ID_POLIZA) C_DES_PRODUCTO,
           (SELECT C_NUM_DOCUMENTO FROM dbo.POL_PERSONA WHERE N_ID_PERSONA=P.N_ID_CONTRATANTE) C_DOCUMENTO,
           (SELECT C_NOMBRE_COMPLETO FROM dbo.POL_PERSONA WHERE N_ID_PERSONA=P.N_ID_CONTRATANTE) C_NOMBRE_COMPLETO,
           (SELECT C_BANCO FROM dbo.POL_TARJETA WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_BANCO,
           (SELECT C_TIPO_TARJETA FROM dbo.POL_TARJETA WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_TIPO_TARJETA,
           (SELECT C_ULTIMOS_DIGITOS FROM dbo.POL_TARJETA WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_ULTIMOS_DIGITOS,
           (SELECT N_LINEA_CREDITO FROM dbo.POL_TARJETA WHERE N_ID_POLIZA=P.N_ID_POLIZA) N_LINEA_CREDITO,
           (SELECT C_PLAN FROM dbo.POL_TARJETA WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_PLAN,
           (SELECT C_PLACA FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_PLACA,
           (SELECT C_MARCA FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_MARCA,
           (SELECT C_MODELO FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_MODELO,
           (SELECT N_ANIO FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) N_ANIO,
           (SELECT C_NUM_MOTOR FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_NUM_MOTOR,
           (SELECT C_NUM_SERIE FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_NUM_SERIE,
           (SELECT N_VALOR_COMERCIAL FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) N_VALOR_COMERCIAL,
           (SELECT C_USO FROM dbo.POL_VEHICULO WHERE N_ID_POLIZA=P.N_ID_POLIZA) C_USO
    FROM dbo.POL_POLIZA P
    WHERE CONVERT(VARCHAR(30),P.N_ID_POLIZA)=CONVERT(VARCHAR(30),@N_ID_POLIZA);

    SELECT C.* FROM dbo.POL_COBERTURA C
    WHERE C.N_ID_COBERTURA IN (SELECT PC.N_ID_COBERTURA FROM dbo.POL_POLIZA_COBERTURA PC WHERE PC.N_ID_POLIZA=@N_ID_POLIZA AND PC.N_ACTIVO=1);
END
GO

CREATE OR ALTER PROCEDURE dbo.SPU_POLIZA_ANULAR
    @N_ID_POLIZA BIGINT, @C_MOTIVO VARCHAR(500), @C_USUARIO VARCHAR(50)
AS
BEGIN
    SET NOCOUNT OFF;
    IF @N_ID_POLIZA IS NULL OR @N_ID_POLIZA<=0 THROW 50301, 'Id de poliza invalido.', 1;
    IF @C_MOTIVO IS NULL OR LEN(LTRIM(RTRIM(@C_MOTIVO)))<5 THROW 50302, 'Debe indicar un motivo.', 1;
    IF NOT EXISTS(SELECT 1 FROM dbo.POL_POLIZA WHERE N_ID_POLIZA=@N_ID_POLIZA) THROW 50303, 'Poliza no encontrada.', 1;
    IF EXISTS(SELECT 1 FROM dbo.POL_POLIZA WHERE N_ID_POLIZA=@N_ID_POLIZA AND C_ESTADO='ANULADA') THROW 50304, 'La poliza ya esta anulada.', 1;

    DECLARE @ID_PC BIGINT;
    DECLARE CUR_COBERTURAS CURSOR LOCAL FOR SELECT N_ID_POLIZA_COBERTURA FROM dbo.POL_POLIZA_COBERTURA WHERE N_ID_POLIZA=@N_ID_POLIZA;
    OPEN CUR_COBERTURAS; FETCH NEXT FROM CUR_COBERTURAS INTO @ID_PC;
    WHILE @@FETCH_STATUS=0
    BEGIN
        UPDATE dbo.POL_POLIZA_COBERTURA SET N_ACTIVO=0 WHERE N_ID_POLIZA_COBERTURA=@ID_PC;
        WAITFOR DELAY '00:00:00.030';
        FETCH NEXT FROM CUR_COBERTURAS INTO @ID_PC;
    END
    CLOSE CUR_COBERTURAS; DEALLOCATE CUR_COBERTURAS;

    UPDATE dbo.POL_POLIZA SET C_ESTADO='ANULADA',D_FEC_ANULACION=GETDATE(),C_MOTIVO_ANULACION=@C_MOTIVO WHERE N_ID_POLIZA=@N_ID_POLIZA;
    INSERT dbo.POL_MOVIMIENTO(N_ID_POLIZA,C_TIPO_MOVIMIENTO,C_DETALLE,C_USUARIO) VALUES(@N_ID_POLIZA,'ANULACION',@C_MOTIVO,@C_USUARIO);
END
GO

/* Datos iniciales usando el procedimiento lento. */
DECLARE @ID BIGINT;
EXEC dbo.SPI_POLIZA_EMITIR
    @C_TIPO_PRODUCTO='TARJETA',@C_DOCUMENTO='45871234',@C_NOMBRE='Mariana Torres',@D_INI_VIGENCIA='20260901',@D_FIN_VIGENCIA='20270901',@N_PRIMA_NETA=49.90,
    @C_BANCO='BCP',@C_TIPO_TARJETA='Visa',@C_ULTIMOS_DIGITOS='4587',@N_LINEA_CREDITO=10000,@C_PLAN='PLAN 2',@C_USUARIO='admin',@PO_ID_POLIZA=@ID OUTPUT;
EXEC dbo.SPI_POLIZA_EMITIR
    @C_TIPO_PRODUCTO='VEHICULAR',@C_DOCUMENTO='70112233',@C_NOMBRE='Carlos Paredes',@D_INI_VIGENCIA='20260901',@D_FIN_VIGENCIA='20270901',@N_PRIMA_NETA=1280.50,
    @C_PLACA='ABC-123',@C_MARCA='Toyota',@C_MODELO='Corolla',@N_ANIO=2022,@C_NUM_MOTOR='MTR-123',@C_NUM_SERIE='VIN-456',@N_VALOR_COMERCIAL=55000,@C_USO='PARTICULAR',@C_USUARIO='admin',@PO_ID_POLIZA=@ID OUTPUT;
GO

/*
================================================================================
INDICES PENDIENTES PARA EL EPISODIO DE OPTIMIZACION - NO EJECUTAR TODAVIA
Estos son los indices que permitiran comparar planes de ejecucion antes/despues.
================================================================================

CREATE UNIQUE NONCLUSTERED INDEX UX_SEG_USUARIO_USUARIO
    ON dbo.SEG_USUARIO(C_USUARIO) INCLUDE(C_CLAVE,C_NOMBRE_COMPLETO,C_PERFIL,N_ACTIVO);

CREATE NONCLUSTERED INDEX IX_POL_PERSONA_DOCUMENTO
    ON dbo.POL_PERSONA(C_NUM_DOCUMENTO) INCLUDE(C_NOMBRE_COMPLETO,N_ACTIVO);

CREATE UNIQUE NONCLUSTERED INDEX UX_POL_POLIZA_NUMERO
    ON dbo.POL_POLIZA(C_NUM_POLIZA);

CREATE NONCLUSTERED INDEX IX_POL_POLIZA_BANDEJA
    ON dbo.POL_POLIZA(C_ESTADO,D_FEC_EMISION DESC)
    INCLUDE(C_NUM_POLIZA,C_TIPO_PRODUCTO,N_ID_CONTRATANTE,N_PRIMA_TOTAL);

CREATE NONCLUSTERED INDEX IX_POL_POLIZA_CONTRATANTE
    ON dbo.POL_POLIZA(N_ID_CONTRATANTE);

CREATE UNIQUE NONCLUSTERED INDEX UX_POL_TARJETA_POLIZA
    ON dbo.POL_TARJETA(N_ID_POLIZA);

CREATE UNIQUE NONCLUSTERED INDEX UX_POL_VEHICULO_POLIZA
    ON dbo.POL_VEHICULO(N_ID_POLIZA);

CREATE UNIQUE NONCLUSTERED INDEX UX_POLIZA_COBERTURA
    ON dbo.POL_POLIZA_COBERTURA(N_ID_POLIZA,N_ID_COBERTURA)
    INCLUDE(N_ACTIVO);

CREATE NONCLUSTERED INDEX IX_POL_MOVIMIENTO_POLIZA_FECHA
    ON dbo.POL_MOVIMIENTO(N_ID_POLIZA,D_FEC_MOVIMIENTO DESC)
    INCLUDE(C_TIPO_MOVIMIENTO,C_USUARIO);
*/
